name: e_commerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

# package
dependencies:
  flutter:
    sdk: flutter

  # utility package
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0

  # icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # state management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
# package end

flutter:
  uses-material-design: true

  # local assets
  assets:
    - assets/logos
    - assets/icons/brands
    - assets/logos

  # local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica/coolvetica_rg.otf
          weight: 400
        - asset: assets/fonts/coolvetica/coolvetica_rg_it.otf
          weight: 400
          style: italic
